AWSTemplateFormatVersion: 2010-09-09

Parameters:
  TemplateBucketName:
    Type: String
    Default: [bucket-name]
    
  Prefix:
    Type: String
    Default: dva-03-008
    
  BatchSize:
    Type: Number
    Default: 1
    
  LambdaHandler:
    Type: String
    Default: index.lambda_handler

  LambdaMemorySize:
    Type: Number
    Default: 128
    
  LambdaRuntime:
    Type: String
    Default: python3.8
    
  LambdaTimeout:
    Type: Number
    Default: 20
    
    
Resources:
  SQSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-sqs.yaml"
      Parameters:
        Prefix: !Ref Prefix
        ReceiveMessageWaitTimeSeconds: 20
        VisibilityTimeout: 90

  LambdaStack1:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - SQSStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-lambda-01.yaml"
      Parameters:
        FifoQueueArn: !GetAtt SQSStack.Outputs.FifoQueueArn
        FifoQueueUrl: !GetAtt SQSStack.Outputs.FifoQueueUrl
        LambdaHandler: !Ref LambdaHandler
        LambdaMemorySize: !Ref LambdaMemorySize
        LambdaRuntime: !Ref LambdaRuntime
        LambdaTimeout: !Ref LambdaTimeout
        Prefix: !Ref Prefix
        StandardQueueArn: !GetAtt SQSStack.Outputs.StandardQueueArn
        StandardQueueUrl: !GetAtt SQSStack.Outputs.StandardQueueUrl
        
  LambdaStack2:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - SQSStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-lambda-02.yaml"
      Parameters:
        BatchSize: !Ref BatchSize
        FifoQueueArn: !GetAtt SQSStack.Outputs.FifoQueueArn
        LambdaHandler: !Ref LambdaHandler
        LambdaMemorySize: !Ref LambdaMemorySize
        LambdaRuntime: !Ref LambdaRuntime
        LambdaTimeout: !Ref LambdaTimeout
        Prefix: !Ref Prefix
        StandardQueueArn: !GetAtt SQSStack.Outputs.StandardQueueArn
