AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String
    
  ReceiveMessageWaitTimeSeconds:
    Type: Number
    
  VisibilityTimeout:
    Type: Number
    

Resources:
  StandardQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Prefix}-standard"
      ReceiveMessageWaitTimeSeconds: !Ref ReceiveMessageWaitTimeSeconds
      VisibilityTimeout: !Ref VisibilityTimeout
      
  FifoQueue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: true
      FifoQueue: true
      QueueName: !Sub "${Prefix}.fifo"
      ReceiveMessageWaitTimeSeconds: !Ref ReceiveMessageWaitTimeSeconds
      VisibilityTimeout: !Ref VisibilityTimeout
      
      
Outputs:
  StandardQueueUrl:
    Value: !Ref StandardQueue
      
  StandardQueueArn:
    Value: !GetAtt StandardQueue.Arn

  FifoQueueUrl:
    Value: !Ref FifoQueue

  FifoQueueArn:
    Value: !GetAtt FifoQueue.Arn
