AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AvailabilityZone1:
    Type: String
    
  AvailabilityZone2:
    Type: String

  CacheEngine:
    Type: String
  
  CacheEngineVersion:
    Type: String

  CacheNodeType:
    Type: String
    
  CacheParameterGroupName:
    Type: String
    
  CacheSecurityGroup:
    Type: String
    
  CacheSubnet1:
    Type: String
    
  CacheSubnet2:
    Type: String
  
  NumNodeGroups:
    Type: Number
    
  Prefix:
    Type: String
    
  RedisPort:
    Type: Number
    
  ReplicaCount:
    Type: Number


Resources:
  SubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      CacheSubnetGroupName: !Sub "${Prefix}-subnetgroup"
      Description: !Sub "${Prefix}-SubnetGroup"
      SubnetIds:
        - !Ref CacheSubnet1
        - !Ref CacheSubnet2
        
  ReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      AutomaticFailoverEnabled: true
      AutoMinorVersionUpgrade: true
      CacheNodeType: !Ref CacheNodeType
      CacheParameterGroupName: !Ref CacheParameterGroupName
      CacheSubnetGroupName: !Ref SubnetGroup
      Engine: !Ref CacheEngine
      EngineVersion: !Ref CacheEngineVersion
      MultiAZEnabled: true
      NodeGroupConfiguration:
        - PrimaryAvailabilityZone: !Sub "${AWS::Region}${AvailabilityZone1}"
          ReplicaAvailabilityZones:
            - !Sub "${AWS::Region}${AvailabilityZone2}"
          ReplicaCount: !Ref ReplicaCount
      #NumCacheClusters: !Ref NumCacheClusters # Property NumCacheCluster cannot be defined along with Properties NumNodeGroups, ReplicasPerNodeGroup or NodeGroupConfiguration
      NumNodeGroups: !Ref NumNodeGroups
      Port: !Ref RedisPort
      ReplicationGroupDescription: !Sub "${Prefix}-ReplicationGroup"
      ReplicationGroupId: !Sub "${Prefix}-replicationgroup"
      SecurityGroupIds:
        - !Ref CacheSecurityGroup
        
Outputs:
  ConfigurationEndPointAddress:
    Value: !GetAtt ReplicationGroup.ConfigurationEndPoint.Address
