AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dva-01-001

  Sample SAM Template for dva-01-001
  
Parameters:
  Prefix:
    Type: String
    Default: dva-01-001

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Role: !GetAtt HelloWorldFunctionRole.Arn
      Runtime: python3.8
      Events:
        HelloWorld:
          #Type: Api
          Type: HttpApi
          Properties:
            Path: /hello
            Method: get
            
  HelloWorldFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: HelloWorldFunctionPolicies
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:List*
                  - dynamodb:DescribeReservedCapacity*
                  - dynamodb:DescribeLimits
                  - dynamodb:DescribeTimeToLive
                Resource: "*"
              - Effect: Allow
                Action:
                  #- dynamodb:BatchGet*
                  #- dynamodb:DescribeStream
                  #- dynamodb:DescribeTable
                  #- dynamodb:Get*
                  #- dynamodb:Query
                  - dynamodb:Scan
                  #- dynamodb:BatchWrite*
                  #- dynamodb:CreateTable
                  #- dynamodb:Delete*
                  #- dynamodb:Update*
                  #- dynamodb:PutItem
                Resource: !GetAtt Table.Arn
            
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: dt
        Type: String
      #ProvisionedThroughput:
      TableName: !Sub ${Prefix}-Table
      
      
  #SampleTable:
  #  Type: AWS::DynamoDB::Table
  #  Properties:
  #    AttributeDefinitions:
  #      - AttributeName: dt
  #        AttributeType: S
  #    BillingMode: PAY_PER_REQUEST
  #    KeySchema:
  #      - AttributeName: dt
  #        KeyType: HASH
  #    TableName: !Sub ${Prefix}-SampleTable
