AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String
    

Resources:
  Key:
    Type: AWS::KMS::Key
    Properties:
      #BypassPolicyLockoutSafetyCheck: Boolean
      #Description: String
      Enabled: true
      #EnableKeyRotation: Boolean
      KeyPolicy:
        Version: 2012-10-17
        #Id: !Sub "${Prefix}-cmk"
        Id: !Ref Prefix
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"
            Condition:
              StringEquals:
                kms:ViaService: !Sub "kinesis.${AWS::Region}.amazonaws.com"
                kms:CallerAccount: !Ref AWS::AccountId
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "*"
            Resource: "*"
      KeySpec: SYMMETRIC_DEFAULT
      KeyUsage: ENCRYPT_DECRYPT
      #MultiRegion: Boolean
      Origin: AWS_KMS
      PendingWindowInDays: 7
      #Tags: 
      #  - Tag


Outputs:
  #BucketName:
  #  Value: !Ref Bucket
  
  #BucketArn:
  #  Value: !GetAtt Bucket.Arn
  
  KeyArn:
    Value: !GetAtt Key.Arn
