AWSTemplateFormatVersion: 2010-09-09

Parameters:
  TemplateBucketName:
    Type: String
    Default: awstut-bucket
    
  Prefix:
    Type: String
    Default: dva-03-010

  IAMUserPassword:
    Type: String
    Default: P@ssw0rd
    
  KinesisShardCount:
    Type: Number
    Default: 1
    
  LambdaArchitecture:
    Type: String
    Default: arm64
    
  LambdaEphemeralStorageSize:
    Type: Number
    Default: 512
    
  LambdaHandler:
    Type: String
    Default: index.lambda_handler
    
  LambdaLayerPackage:
    Type: String
    Default: layer.zip
    
  LambdaRuntime:
    Type: String
    Default: python3.8
    
  LambdaTimeout:
    Type: Number
    Default: 300
    
  OpenSearchIndexName:
    Type: String
    Default: test-stock-index


Resources:
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-iam.yaml"
      Parameters:
        Password: !Ref IAMUserPassword
        Prefix: !Ref Prefix
        
  OpenSearchStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - IAMStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-opensearch.yaml"
      Parameters:
        CollectionName: !Sub "${Prefix}-collection"
        FunctionRoleArn2: !GetAtt IAMStack.Outputs.FunctionRoleArn2
        KinesisOpenSearchServerlessDestinationRoleArn: !GetAtt IAMStack.Outputs.KinesisOpenSearchServerlessDestinationRoleArn
        OpenSearchIndexName: !Ref OpenSearchIndexName
        Prefix: !Ref Prefix
        UserArn: !GetAtt IAMStack.Outputs.UserArn
        
  SSMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-ssm.yaml"
      Parameters:
        Prefix: !Ref Prefix
        
  LambdaStack1:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - SSMStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-lambda-01.yaml"
      Parameters:
        Architecture: !Ref LambdaArchitecture
        CodeS3Bucket: !Ref TemplateBucketName
        EphemeralStorageSize: !Ref LambdaEphemeralStorageSize
        Handler: !Ref LambdaHandler
        LayerPackage: !Ref LambdaLayerPackage
        Prefix: !Ref Prefix
        RequirementsParameter: !GetAtt SSMStack.Outputs.RequirementsParameter
        Runtime: !Ref LambdaRuntime
        Timeout: !Ref LambdaTimeout
        
  LambdaStack2:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - LambdaStack1
      - OpenSearchStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-lambda-02.yaml"
      Parameters:
        Architecture: !Ref LambdaArchitecture
        Collection: !GetAtt OpenSearchStack.Outputs.Collection
        FunctionRoleArn2: !GetAtt IAMStack.Outputs.FunctionRoleArn2
        Handler: !Ref LambdaHandler
        LambdaLayer: !GetAtt LambdaStack1.Outputs.LambdaLayer
        OpenSearchIndexName: !Ref OpenSearchIndexName
        Prefix: !Ref Prefix
        Runtime: !Ref LambdaRuntime
        
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-s3.yaml"
      Parameters:
        Prefix: !Ref Prefix
        
  KinesisStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - OpenSearchStack
      - S3Stack
      - LambdaStack2
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-kinesis.yaml"
      Parameters:
        BucketName: !GetAtt S3Stack.Outputs.BucketName
        CollectionEndpoint: !GetAtt OpenSearchStack.Outputs.CollectionEndpoint
        KinesisOpenSearchServerlessDestinationRoleArn: !GetAtt IAMStack.Outputs.KinesisOpenSearchServerlessDestinationRoleArn
        OpenSearchIndexName: !Ref OpenSearchIndexName
        ShardCount: !Ref KinesisShardCount
        Prefix: !Ref Prefix
        
  LambdaStack3:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - KinesisStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-lambda-03.yaml"
      Parameters:
        Architecture: !Ref LambdaArchitecture
        Handler: !Ref LambdaHandler
        KinesisDataStreamName: !GetAtt KinesisStack.Outputs.KinesisDataStreamName
        Prefix: !Ref Prefix
        Runtime: !Ref LambdaRuntime
        Timeout: !Ref LambdaTimeout
