AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ResizeBucketName:
    Type: String
    
  ThumbnailFunctionArn:
    Type: String
    
  UploadBucketName:
    Type: String
    

Resources:
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref UploadBucketName
      NotificationConfiguration:
        LambdaConfigurations: 
          - Event: "s3:ObjectCreated:*"
            Function: !Ref ThumbnailFunctionArn

  ResizeBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref ResizeBucketName
