AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String
    
    
Resources:
  RequirementsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref Prefix
      Type: String
      Value: |
        Pillow
        
      
Outputs:
  RequirementsParameter:
    Value: !Ref RequirementsParameter