AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Handler:
    Type: String

  Prefix:
    Type: String
    
  Runtime:
    Type: String
    

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref Prefix
      NotificationConfiguration:
        EventBridgeConfiguration: 
          EventBridgeEnabled: true


Outputs:
  BucketName:
    Value: !Ref Bucket
