AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Function1:
    Type: String
    
  Function2:
    Type: String
    
  Function3:
    Type: String
    
  FunctionArn1:
    Type: String
    
  FunctionArn2:
    Type: String
    
  FunctionArn3:
    Type: String
    
  Prefix:
    Type: String
    
    
Resources:
  Rule1:
    Type: AWS::Events::Rule
    Properties: 
      Name: !Sub "${Prefix}-EventsRule-01"
      ScheduleExpression: rate(1 minute)
      State: ENABLED
      Targets: 
        - Arn: !Ref FunctionArn1
          Id: !Ref Function1
          
  Rule2:
    Type: AWS::Events::Rule
    Properties: 
      Name: !Sub "${Prefix}-EventsRule-02"
      ScheduleExpression: rate(1 minute)
      State: ENABLED
      Targets: 
        - Arn: !Ref FunctionArn2
          Id: !Ref Function2
          
  Rule3:
    Type: AWS::Events::Rule
    Properties: 
      Name: !Sub "${Prefix}-EventsRule-03"
      ScheduleExpression: rate(1 minute)
      State: ENABLED
      Targets: 
        - Arn: !Ref FunctionArn3
          Id: !Ref Function3
  
  EventsRulePermission1: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref Function1
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt Rule1.Arn
      
  EventsRulePermission2: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref Function2
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt Rule2.Arn
      
  EventsRulePermission3: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref Function3
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt Rule3.Arn
