AWSTemplateFormatVersion: 2010-09-09

Parameters:
  CloudWatchMetricDimensionName:
    Type: String
    
  CloudWatchMetricDimensionValue:
    Type: String
    
  CloudWatchMetricName:
    Type: String
    
  CloudWatchMetricNamespace:
    Type: String
    
  Function:
    Type: String

  SNSTopicArn:
    Type: String
    
  Prefix:
    Type: String
    
    
Resources:
  Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties: 
      ActionsEnabled: true
      AlarmActions: 
        - !Ref SNSTopicArn
      AlarmDescription: test alarm
      AlarmName: !Ref Prefix
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions: 
        - Name: !Ref CloudWatchMetricDimensionName
          Value: !Ref CloudWatchMetricDimensionValue
      EvaluationPeriods: 2
      InsufficientDataActions: 
        - !Ref SNSTopicArn
      MetricName: !Ref CloudWatchMetricName
      Namespace: !Ref CloudWatchMetricNamespace
      OKActions: 
        - !Ref SNSTopicArn
      Period: 60
      Statistic: Average
      Threshold: 7.0
      Unit: Count
