AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String
    

Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: session-id
          AttributeType: S
        #- AttributeName: comment
        #  AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: session-id
          KeyType: HASH
      TableName: !Sub "${Prefix}-table"


Outputs:
  Table:
    Value: !Ref Table