AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String
    Default: dva-03-002
    

Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: user
          AttributeType: S
        - AttributeName: service
          AttributeType: S
        - AttributeName: datetime
          AttributeType: S
        - AttributeName: rating
          AttributeType: N
        #- AttributeName: comment
        #  AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: gsi-service-rating
          KeySchema:
            - AttributeName: service
              KeyType: HASH
            - AttributeName: rating
              KeyType: RANGE
          Projection:
            NonKeyAttributes:
              - user
              - comment
            ProjectionType: INCLUDE
      KeySchema:
        - AttributeName: user
          KeyType: HASH
        - AttributeName: service
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: lsi-user-datetime
          KeySchema:
            - AttributeName: user
              KeyType: HASH
            - AttributeName: datetime
              KeyType: RANGE
          Projection:
            NonKeyAttributes:
              - service
              - comment
            ProjectionType: INCLUDE
      TableName: !Sub ${Prefix}-table
