AWSTemplateFormatVersion: 2010-09-09

Parameters:
  TemplateBucketName:
    Type: String
    Default: awstut-bucket
    
  Prefix:
    Type: String
    Default: dva-03-003
    
  IndexHtml:
    Type: String
    Default: index.html
    
  SigninHtml:
    Type: String
    Default: signin.html
    
  SignoutHtml:
    Type: String
    Default: signout.html
    

Resources:
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-s3.yaml"
      Parameters:
        Prefix: !Ref Prefix
        IndexHtml: !Ref IndexHtml
        SignoutHtml: !Ref SignoutHtml
  
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-lambda.yaml"
      Parameters:
        Prefix: !Ref Prefix
        
  CognitoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-cognito.yaml"
      Parameters:
        BucketArn: !GetAtt S3Stack.Outputs.BucketArn
        BucketWesSiteEndpointUrl: !GetAtt S3Stack.Outputs.BucketWesSiteEndpointUrl
        Prefix: !Ref Prefix
        SigninHtml: !Ref SigninHtml
        SignoutHtml: !Ref SignoutHtml
        AuthenticatedFunctionArn: !GetAtt LambdaStack.Outputs.AuthenticatedFunctionArn
        UnauthenticatedFunctionArn: !GetAtt LambdaStack.Outputs.UnauthenticatedFunctionArn
