AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String
    Default: dva-05-001


Resources:
  NormalBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Prefix}-normal-bucket
      AccessControl: Private
      LoggingConfiguration:
        DestinationBucketName: !Ref LogBucket
        LogFilePrefix: test-normal-log
        
  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Prefix}-log-bucket
      AccessControl: LogDeliveryWrite
      
      
  ErrorBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Prefix}-error-bucket
      AccessControl: LogDeliveryWrite
